import {
  Package,
  Users,
  BarChart3,
  Smartphone,
  Headphones,
  Database,
  Zap,
  Shield,
  CreditCard,
  Globe,
  Network,
  Banknote,
  AppWindow,
} from "lucide-react";

export const plans = [
  {
    color: "--secondary",
    name: "Free",
    price: "KES 0",
    period: "/month",
    annualPrice: "KES 0/year",
    description: "Free forever",
    badge: null,
    features: [
      { name: "1000 products", icon: Package, included: true },
      { name: "3 roles", icon: Shield, included: true },
      { name: "2 stores", icon: Globe, included: true },
      { name: "3 users", icon: Users, included: true },
      { name: "Email support", icon: Headphones, included: true },
      { name: "Basic reports", icon: Database, included: true },
      { name: "Barcode scanning", icon: Smartphone, included: true },
      { name: "Basic inventory tracking", icon: BarChart3, included: true },
      { name: "Advanced Analytics", icon: BarChart3, included: false },
      { name: "API access", icon: Zap, included: false },
      { name: "ETIMS (KRA) integration", icon: CreditCard, included: false },
      { name: "Warehouse automation", icon: Zap, included: false },
    ],
    buttonText: "Get started",
    buttonVariant: "outline" as const,
  },
  {
    color: "--primary",
    name: "Basic",
    price: "KES 549",
    period: "/month",
    annualPrice: "KES 5,999/year",
    description: "Perfect for small businesses just getting started",
    badge: null,
    features: [
      { name: "1500 products", icon: Package, included: true },
      { name: "6 roles", icon: Shield, included: true },
      { name: "4 stores", icon: Globe, included: true },
      { name: "6 user", icon: Users, included: true },
      { name: "Email support", icon: Headphones, included: true },
      { name: "Basic reports", icon: Database, included: true },
      { name: "Barcode scanning", icon: Smartphone, included: true },
      { name: "Basic inventory tracking", icon: BarChart3, included: true },
      { name: "Advanced Analytics", icon: BarChart3, included: false },
      { name: "API access", icon: Zap, included: false },
      { name: "ETIMS (KRA) integration", icon: CreditCard, included: false },
      { name: "Warehouse automation", icon: Zap, included: false },
    ],
    buttonText: "Start 15-day Trail",
    buttonVariant: "outline" as const,
  },
  {
    color: "--accent",
    name: "Professional",
    price: "KES 1,949",
    period: "/month",
    annualPrice: "KES 22,849/year",
    description: "Ideal for growing businesses with multiple locations",
    badge: "Most Popular",
    features: [
      { name: "2500 products", icon: Package, included: true },
      { name: "12 roles", icon: Shield, included: true },
      { name: "8 stores", icon: Globe, included: true },
      { name: "12 users", icon: Users, included: true },
      { name: "Email support", icon: Headphones, included: true },
      { name: "Barcode scanning", icon: Smartphone, included: true },
      {
        name: "Advanced Inventory Tracking",
        icon: BarChart3,
        included: true,
      },
      { name: "Advanced Analytics", icon: BarChart3, included: true },
      { name: "Basic reports", icon: Database, included: true },
      { name: "API access", icon: Zap, included: false },
      { name: "ETIMS (KRA) integration", icon: CreditCard, included: false },
      { name: "Warehouse automation", icon: Zap, included: false },
    ],
    buttonText: "Start 15-day Trail",
    buttonVariant: "default" as const,
  },
  {
    color: "--chart-4",
    name: "Advanced",
    price: "KES 4,999",
    period: "/month",
    annualPrice: "KES 57,999/year",
    description: "For medium businesses needing enhanced capabilities",
    badge: "Recommended",
    features: [
      { name: "3000 products", icon: Package, included: true },
      { name: "16 roles", icon: Shield, included: true },
      { name: "12 stores", icon: Globe, included: true },
      { name: "16 users", icon: Users, included: true },
      {
        name: "Enterprise inventory management",
        icon: BarChart3,
        included: true,
      },
      { name: "Barcode + RFID", icon: Smartphone, included: true },
      { name: "SKU access", icon: Database, included: true },
      { name: "Advanced Analytics", icon: BarChart3, included: true },
      { name: "API access", icon: Zap, included: true },
      { name: "ETIMS (KRA) integration", icon: CreditCard, included: false },
      { name: "Warehouse automation", icon: Zap, included: false },
      { name: "Custom reports", icon: Database, included: false },
    ],
    buttonText: "Start 15-day Trail",
    buttonVariant: "default" as const,
  },
  {
    color: "--secondary",
    name: "Enterprise",
    price: "Custom",
    period: "/month",
    description: "Custom pricing for large businesses with complex needs",
    badge: "Advanced",
    features: [
      { name: "Unlimited products", icon: Package, included: true },
      { name: "Unlimited roles", icon: Shield, included: true },
      { name: "Unlimited stores", icon: Globe, included: true },
      { name: "Unlimited users", icon: Users, included: true },
      { name: "Access log auditing", icon: Shield, included: true },
      { name: "API access", icon: Zap, included: true },
      { name: "SKU access", icon: Database, included: true },
      { name: "Custom reports", icon: Database, included: true },
      { name: "ETIMS (KRA) integration", icon: CreditCard, included: true },
      { name: "Barcode + RFID + Barcodes", icon: Smartphone, included: true },
      { name: "IP Address Management", icon: Network, included: true },
      { name: "Bank Integration", icon: Banknote, included: true },
      { name: "Mpesa Till Integration", icon: CreditCard, included: true },
      { name: "Application", icon: AppWindow, included: true },

      {
        name: "Enterprise inventory management",
        icon: BarChart3,
        included: true,
      },
      { name: "Warehouse automation", icon: Zap, included: true },
      { name: "Custom prices", icon: Shield, included: true },
    ],
    buttonText: "Start 15-day Trail",
    buttonVariant: "outline" as const,
  },
];
