import {
  BarChart3,
  Store,
  UserCheck,
  Shield,
  Database,
  Zap,
  Crown,
  Building2,
  TrendingUp,
  Users,
  Mail,
} from "lucide-react";

export const packagePlans = [
  {
    id: "BASIC",
    name: "Basic",
    price: "599",
    currency: "KES",
    period: "month",
    description: "Perfect for small businesses getting started",
    popular: false,
    features: [
      { icon: Database, text: "Up to 500 products" },
      { icon: BarChart3, text: "Basic analysis" },
      { icon: TrendingUp, text: "Basic reports" },
      { icon: Store, text: "1 store" },
      { icon: Users, text: "1 user" },
      { icon: UserCheck, text: "1 role" },
      { icon: Shield, text: "Basic security" },
      { icon: Mail, text: "Email support" },
    ],
  },
  {
    id: "PROFESSIONAL",
    name: "Professional",
    price: "1499",
    currency: "KES",
    period: "month",
    description: "Ideal for growing businesses with multiple locations",
    popular: true,
    features: [
      { icon: Database, text: "Up to 4,000 products" },
      { icon: TrendingUp, text: "Advanced inventory tracking" },
      { icon: BarChart3, text: "Advanced analytics" },
      { icon: Users, text: "Up to 5 users" },
      { icon: Store, text: "3 stores" },
      { icon: UserCheck, text: "5 roles" },
      { icon: Zap, text: "Real-time sync" },
      { icon: Shield, text: "Enhanced security" },
    ],
  },
  {
    id: "ADVANCED",
    name: "Advanced",
    price: "2499",
    currency: "KES",
    period: "month",
    description: "For established businesses with complex needs",
    popular: false,
    features: [
      { icon: Database, text: "Unlimited products" },
      { icon: TrendingUp, text: "Advanced forecasting" },
      { icon: BarChart3, text: "Custom reports" },
      { icon: Users, text: "10 users" },
      { icon: Store, text: "8 stores" },
      { icon: UserCheck, text: "10 roles" },
      { icon: Zap, text: "API access" },
      { icon: Crown, text: "Priority support" },
    ],
  },
  {
    id: "ENTERPRISE",
    name: "Enterprise",
    price: "Custom",
    currency: "",
    period: "",
    description: "Tailored solutions for large organizations",
    popular: false,
    features: [
      { icon: Database, text: "Unlimited products" },
      { icon: Users, text: "Unlimited users" },
      { icon: Store, text: "Unlimited stores" },
      { icon: UserCheck, text: "Unlimited roles" },
      { icon: Building2, text: "Multi-tenant support" },
      { icon: Shield, text: "Enterprise security" },
      { icon: Zap, text: "Custom integrations" },
      { icon: Crown, text: "Dedicated support" },
    ],
  },
];
