import {
  BarChart3,
  Shield,
  Database,
  Zap,
  Users,
  Package,
  Globe,
  Headphones,
  Smartphone,
  CreditCard,
  Network,
  Banknote,
  AppWindow,
} from "lucide-react";

export const packagePlans = [
  {
    id: "FREE",
    name: "Free",
    price: "0",
    currency: "KES",
    period: "month",
    description: "Free forever",
    popular: false,
    features: [
      { text: "1000 products", icon: Package, included: true },
      { text: "3 roles", icon: Shield, included: true },
      { text: "2 stores", icon: Globe, included: true },
      { text: "3 users", icon: Users, included: true },
      { text: "Email support", icon: Headphones, included: true },
      { text: "Basic reports", icon: Database, included: true },
      { text: "Barcode scanning", icon: Smartphone, included: true },
      { text: "Basic inventory tracking", icon: BarChart3, included: true },
      { text: "Advanced Analytics", icon: BarChart3, included: false },
      { text: "API access", icon: Zap, included: false },
      { text: "ETIMS (KRA) integration", icon: CreditCard, included: false },
      { text: "Warehouse automation", icon: Zap, included: false },
    ],
    buttonText: "Start Free Trial",
    buttonVariant: "outline" as const,
  },
  {
    id: "BASIC",
    name: "Basic",
    price: "549",
    currency: "KES",
    period: "month",
    description: "Perfect for small businesses just getting started",
    popular: false,
    features: [
      { text: "1500 products", icon: Package, included: true },
      { text: "6 roles", icon: Shield, included: true },
      { text: "4 stores", icon: Globe, included: true },
      { text: "6 users", icon: Users, included: true },
      { text: "Email support", icon: Headphones, included: true },
      { text: "Basic reports", icon: Database, included: true },
      { text: "Barcode scanning", icon: Smartphone, included: true },
      { text: "Basic inventory tracking", icon: BarChart3, included: true },
      { text: "Advanced Analytics", icon: BarChart3, included: false },
      { text: "API access", icon: Zap, included: false },
      { text: "ETIMS (KRA) integration", icon: CreditCard, included: false },
      { text: "Warehouse automation", icon: Zap, included: false },
    ],
    buttonText: "Start Free Trial",
    buttonVariant: "outline" as const,
  },
  {
    id: "PROFESSIONAL",
    name: "Professional",
    price: "1,949",
    currency: "KES",
    period: "month",
    description: "Ideal for growing businesses with multiple locations",
    popular: true,
    features: [
      { text: "2500 products", icon: Package, included: true },
      { text: "12 roles", icon: Shield, included: true },
      { text: "8 stores", icon: Globe, included: true },
      { text: "12 users", icon: Users, included: true },
      { text: "Email support", icon: Headphones, included: true },
      { text: "Barcode scanning", icon: Smartphone, included: true },
      {
        text: "Advanced Inventory Tracking",
        icon: BarChart3,
        included: true,
      },
      { text: "Advanced Analytics", icon: BarChart3, included: true },
      { text: "Basic reports", icon: Database, included: true },
      { text: "API access", icon: Zap, included: false },
      { text: "ETIMS (KRA) integration", icon: CreditCard, included: false },
      { text: "Warehouse automation", icon: Zap, included: false },
    ],
    buttonText: "Get Started",
    buttonVariant: "default" as const,
  },
  {
    id: "ADVANCED",
    name: "Advanced",
    price: "4,999",
    currency: "KES",
    period: "month",
    description: "For medium businesses needing enhanced capabilities",
    popular: false,
    features: [
      { text: "3,000 products", icon: Package, included: true },
      { text: "16 roles", icon: Shield, included: true },
      { text: "12 stores", icon: Globe, included: true },
      { text: "16 users", icon: Users, included: true },
      {
        text: "Enterprise inventory management",
        icon: BarChart3,
        included: true,
      },
      { text: "Barcode + RFID", icon: Smartphone, included: true },
      { text: "SKU access", icon: Database, included: true },
      { text: "Advanced Analytics", icon: BarChart3, included: true },
      { text: "API access", icon: Zap, included: true },
      { text: "ETIMS (KRA) integration", icon: CreditCard, included: false },
      { text: "Warehouse automation", icon: Zap, included: false },
      { text: "Custom reports", icon: Database, included: false },
    ],
    buttonText: "Get Started",
    buttonVariant: "default" as const,
  },
  {
    id: "ENTERPRISE",
    name: "Enterprise",
    price: "Custom",
    currency: "KES",
    period: "month",
    description: "Custom pricing for large businesses with complex needs",
    popular: false,
    features: [
      { text: "Unlimited products", icon: Package, included: true },
      { text: "Unlimited roles", icon: Shield, included: true },
      { text: "Unlimited stores", icon: Globe, included: true },
      { text: "Unlimited users", icon: Users, included: true },
      { text: "Access log auditing", icon: Shield, included: true },
      { text: "API access", icon: Zap, included: true },
      { text: "SKU access", icon: Database, included: true },
      { text: "Custom reports", icon: Database, included: true },
      { text: "ETIMS (KRA) integration", icon: CreditCard, included: true },
      { text: "Barcode + RFID + Barcodes", icon: Smartphone, included: true },
      { text: "IP Address Management", icon: Network, included: true },
      { text: "Bank Integration", icon: Banknote, included: true },
      { text: "Mpesa Till Integration", icon: CreditCard, included: true },
      { text: "Application", icon: AppWindow, included: true },

      {
        text: "Enterprise inventory management",
        icon: BarChart3,
        included: true,
      },
      { text: "Warehouse automation", icon: Zap, included: true },
      { text: "Custom prices", icon: Shield, included: true },
    ],
    buttonText: "Contact Sales",
    buttonVariant: "outline" as const,
  },
];
