import {
  BarChart3,
  Shield,
  Database,
  Zap,
  Users,
  Package,
  Globe,
  Headphones,
  Smartphone,
  CreditCard,
  Network,
  Banknote,
  AppWindow,
} from "lucide-react";

export const packagePlans = [
  {
    id: "BASIC",
    name: "Basic",
    price: "549",
    currency: "KES",
    period: "month",
    description: "Perfect for small businesses just getting started",
    popular: false,
    features: [
      { text: "500 products", icon: Package, included: true },
      { text: "1 role", icon: Shield, included: true },
      { text: "1 store", icon: Globe, included: true },
      { text: "1 user", icon: Users, included: true },
      { text: "Email support", icon: Headphones, included: true },
      { text: "Basic reports", icon: Database, included: true },
      { text: "Barcode scanning", icon: Smartphone, included: true },
      { text: "Basic inventory tracking", icon: BarChart3, included: true },
      { text: "Advanced Analytics", icon: BarChart3, included: false },
      { text: "API access", icon: Zap, included: false },
      { text: "ETIMS (KRA) integration", icon: CreditCard, included: false },
      { text: "Warehouse automation", icon: Zap, included: false },
    ],
    buttonText: "Start Free Trial",
    buttonVariant: "outline" as const,
  },
  {
    id: "PROFESSIONAL",
    name: "Professional",
    price: "1,949",
    currency: "KES",
    period: "month",
    description: "Ideal for growing businesses with multiple locations",
    popular: true,
    features: [
      { text: "900 products", icon: Package, included: true },
      { text: "5 roles", icon: Shield, included: true },
      { text: "4 stores", icon: Globe, included: true },
      { text: "5 users", icon: Users, included: true },
      { text: "Email support", icon: Headphones, included: true },
      { text: "Barcode scanning", icon: Smartphone, included: true },
      {
        text: "Advanced Inventory Tracking",
        icon: BarChart3,
        included: true,
      },
      { text: "Advanced Analytics", icon: BarChart3, included: true },
      { text: "Basic reports", icon: Database, included: true },
      { text: "API access", icon: Zap, included: false },
      { text: "ETIMS (KRA) integration", icon: CreditCard, included: false },
      { text: "Warehouse automation", icon: Zap, included: false },
    ],
    buttonText: "Get Started",
    buttonVariant: "default" as const,
  },
  {
    id: "ADVANCED",
    name: "Advanced",
    price: "4,999",
    currency: "KES",
    period: "month",
    description: "For medium businesses needing enhanced capabilities",
    popular: false,
    features: [
      { text: "1,200 products", icon: Package, included: true },
      { text: "11 roles", icon: Shield, included: true },
      { text: "10 stores", icon: Globe, included: true },
      { text: "11 users", icon: Users, included: true },
      {
        text: "Enterprise inventory management",
        icon: BarChart3,
        included: true,
      },
      { text: "Barcode + RFID", icon: Smartphone, included: true },
      { text: "SKU access", icon: Database, included: true },
      { text: "Advanced Analytics", icon: BarChart3, included: true },
      { text: "API access", icon: Zap, included: true },
      { text: "ETIMS (KRA) integration", icon: CreditCard, included: false },
      { text: "Warehouse automation", icon: Zap, included: false },
      { text: "Custom reports", icon: Database, included: false },
    ],
    buttonText: "Get Started",
    buttonVariant: "default" as const,
  },
  {
    id: "ENTERPRISE",
    name: "Enterprise",
    price: "Custom",
    currency: "KES",
    period: "month",
    description: "Custom pricing for large businesses with complex needs",
    popular: false,
    features: [
      { text: "Unlimited products", icon: Package, included: true },
      { text: "Unlimited roles", icon: Shield, included: true },
      { text: "Unlimited stores", icon: Globe, included: true },
      { text: "Unlimited users", icon: Users, included: true },
      { text: "Access log auditing", icon: Shield, included: true },
      { text: "API access", icon: Zap, included: true },
      { text: "SKU access", icon: Database, included: true },
      { text: "Custom reports", icon: Database, included: true },
      { text: "ETIMS (KRA) integration", icon: CreditCard, included: true },
      { text: "Barcode + RFID + Barcodes", icon: Smartphone, included: true },
      { text: "IP Address Management", icon: Network, included: true },
      { text: "Bank Integration", icon: Banknote, included: true },
      { text: "Mpesa Till Integration", icon: CreditCard, included: true },
      { text: "Application", icon: AppWindow, included: true },

      {
        text: "Enterprise inventory management",
        icon: BarChart3,
        included: true,
      },
      { text: "Warehouse automation", icon: Zap, included: true },
      { text: "Custom prices", icon: Shield, included: true },
    ],
    buttonText: "Contact Sales",
    buttonVariant: "outline" as const,
  },
];

//   export const packagePlans = [
//   {
//     id: "BASIC",
//     name: "Basic",
//     price: "599",
//     currency: "KES",
//     period: "month",
//     description: "Perfect for small businesses getting started",
//     popular: false,
//     features: [
//       { icon: Database, text: "Up to 500 products" },
//       { icon: BarChart3, text: "Basic analysis" },
//       { icon: TrendingUp, text: "Basic reports" },
//       { icon: Store, text: "1 store" },
//       { icon: Users, text: "1 user" },
//       { icon: UserCheck, text: "1 role" },
//       { icon: Shield, text: "Basic security" },
//       { icon: Mail, text: "Email support" },
//     ],
//   },
//   {
//     id: "PROFESSIONAL",
//     name: "Professional",
//     price: "1499",
//     currency: "KES",
//     period: "month",
//     description: "Ideal for growing businesses with multiple locations",
//     popular: true,
//     features: [
//       { icon: Database, text: "Up to 4,000 products" },
//       { icon: TrendingUp, text: "Advanced inventory tracking" },
//       { icon: BarChart3, text: "Advanced analytics" },
//       { icon: Users, text: "Up to 5 users" },
//       { icon: Store, text: "3 stores" },
//       { icon: UserCheck, text: "5 roles" },
//       { icon: Zap, text: "Real-time sync" },
//       { icon: Shield, text: "Enhanced security" },
//     ],
//   },
//   {
//     id: "ADVANCED",
//     name: "Advanced",
//     price: "2499",
//     currency: "KES",
//     period: "month",
//     description: "For established businesses with complex needs",
//     popular: false,
//     features: [
//       { icon: Database, text: "Unlimited products" },
//       { icon: TrendingUp, text: "Advanced forecasting" },
//       { icon: BarChart3, text: "Custom reports" },
//       { icon: Users, text: "10 users" },
//       { icon: Store, text: "8 stores" },
//       { icon: UserCheck, text: "10 roles" },
//       { icon: Zap, text: "API access" },
//       { icon: Crown, text: "Priority support" },
//     ],
//   },
//   {
//     id: "ENTERPRISE",
//     name: "Enterprise",
//     price: "Custom",
//     currency: "",
//     period: "",
//     description: "Tailored solutions for large organizations",
//     popular: false,
//     features: [
//       { icon: Database, text: "Unlimited products" },
//       { icon: Users, text: "Unlimited users" },
//       { icon: Store, text: "Unlimited stores" },
//       { icon: UserCheck, text: "Unlimited roles" },
//       { icon: Building2, text: "Multi-tenant support" },
//       { icon: Shield, text: "Enterprise security" },
//       { icon: Zap, text: "Custom integrations" },
//       { icon: Crown, text: "Dedicated support" },
//     ],
//   },
// ];
