//purchase order data structure
export interface GeneratePurchaseOrderData {
  purchaseOrderNumber: number;
  totalProducts: number;
}

//purchase order response structure
export interface GeneratePurchaseOrderResponse {
  success: boolean;
  message: string;
  data?: GeneratePurchaseOrderData | null;
}

//purchase order summary item structure
export interface PurchaseOrderResponseItem {
  purchaseOrderId: string;
  supplierName: string | null;
  storeName: string | null;
  status: string;
  createdBy: string;
  dateCreated: Date;
  productCount: number;
}

//get purchase order response structure
export interface PurchaseOrderResponse {
  success: boolean;
  message: string;
  data: PurchaseOrderResponseItem[] | null;
}

// Product used in UI
export interface Product {
  id: string; // Local UI-only identifier
  barcode: string | null;
  name: string | null;
  quantity: number;
  price: number;
}

// Product as it comes from the backend (API)
export interface PurchaseOrderProduct {
  barcode: string | null;
  productName: string | null;
  quantity: number;
  price: number;
}

// purchase order data
export interface PurchaseOrderData {
  purchaseOrderId: string;
  supplier: string | null;
  store: string | null;
  status:
    | "DRAFT"
    | "SUBMITTED"
    | "APPROVED"
    | "REJECTED"
    | "RECEIVED"
    | "PARTIAL"
    | "CANCELLED"
    | "CLOSED";
  orderNumber: number;
  dateExpected: string | null;
  autoGenerated: boolean;
  dateCreated: Date;
  createdBy: string;
  products: PurchaseOrderProduct[];
}

// purchase order response
export interface PurchaseOrderDetailResponse {
  success: boolean;
  message: string;
  data: PurchaseOrderData | null;
}
