//purchase order data structure
export interface GeneratePurchaseOrderData {
  purchaseOrderNumber: number;
  totalProducts: number;
}

//purchase order response structure
export interface GeneratePurchaseOrderResponse {
  success: boolean;
  message: string;
  data?: GeneratePurchaseOrderData | null;
}

//purchase order summary item structure
export interface PurchaseOrderResponseItem {
  purchaseOrderId: string;
  supplierName: string | null;
  storeName: string | null;
  status: string;
  createdBy: string;
  dateCreated: Date;
  productCount: number;
}

//get purchase order response structure
export interface PurchaseOrderResponse {
  success: boolean;
  message: string;
  data: PurchaseOrderResponseItem[] | null;
}

// Product used in UI
export interface Product {
  id: string; // Local UI-only identifier
  barcode: string | null;
  name: string | null;
  quantity: number;
  price: number;
}

// Product types
export interface PurchaseOrderProduct {
  businessProductId: string;
  barcode: string | null;
  productName: string | null;
  quantity: number;
  price: number;
}

// purchase order data
export interface PurchaseOrderData {
  purchaseOrderId: string;
  supplier: string | null;
  store: string | null;
  status:
    | "DRAFT"
    | "SUBMITTED"
    | "APPROVED"
    | "REJECTED"
    | "RECEIVED"
    | "PARTIAL"
    | "CANCELLED"
    | "CLOSED";
  orderNumber: number;
  dateExpected: string | null;
  autoGenerated: boolean;
  dateCreated: Date;
  createdBy: string;
  products: PurchaseOrderProduct[];
}

// purchase order response
export interface PurchaseOrderDetailResponse {
  success: boolean;
  message: string;
  data: PurchaseOrderData | null;
}

//update purchase order response data
export type UpdatePurchaseOrderData = {
  purchaseOrderId: string;
  updatedAt: string;
};

//update purchase order response structure
export type UpdatePurchaseOrderResponse = {
  success: boolean;
  message: string;
  data: UpdatePurchaseOrderData | null;
};

//single product
export type BusinessProductResult = {
  businessProductId: string;
  productName: string | null;
  productBarcode: string | null;
  price: number;
};

// Generic API response wrapper
export type SearchBusinessProductResponse = {
  success: boolean;
  message: string;
  data: BusinessProductResult[] | null;
};

//create purchase order data structure
export interface CreatePurchaseOrderData {
  purchaseOrderNumber: number;
  totalProducts: number;
}

//create purchase order response structure
export interface CreatePurchaseOrderResponse {
  success: boolean;
  message: string;
  data: CreatePurchaseOrderData | null;
}
