"use client";
import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
  Image,
} from "@react-pdf/renderer";

// Types
export interface PurchaseOrderProduct {
  businessProductId: string;
  barcode: string | null;
  productName: string | null;
  quantity: number;
  price: number;
}

export interface PurchaseOrderData {
  purchaseOrderId: string;
  supplier: string | null;
  store: string | null;
  status:
    | "DRAFT"
    | "SUBMITTED"
    | "APPROVED"
    | "REJECTED"
    | "RECEIVED"
    | "PARTIAL"
    | "CANCELLED"
    | "CLOSED";
  orderNumber: number;
  dateExpected: string | null;
  autoGenerated: boolean;
  dateCreated: Date;
  createdBy: string;
  products: PurchaseOrderProduct[];
}

export interface CompanyInfo {
  name: string;
  tagline?: string;
  email?: string;
  phone?: string;
  logoUrl?: string;
}

export interface PurchaseOrderPDFProps {
  orderData: PurchaseOrderData;
  companyInfo?: CompanyInfo;
  currency?: string;
  locale?: string;
}

// Styles
const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontSize: 10,
    fontFamily: "Helvetica",
    backgroundColor: "#ffffff",
  },
  header: {
    alignItems: "center",
    marginBottom: 25,
  },
  logo: {
    width: 60,
    height: 60,
    marginBottom: 10,
  },
  companyName: {
    fontSize: 18,
    fontWeight: "bold",
    marginBottom: 4,
  },
  companyTagline: {
    fontSize: 9,
    color: "#666666",
    marginBottom: 2,
  },
  companyContact: {
    fontSize: 8,
    color: "#666666",
    marginTop: 4,
  },
  divider: {
    borderBottom: 2,
    borderBottomColor: "#333333",
    marginVertical: 15,
  },
  title: {
    textAlign: "center",
    fontSize: 14,
    fontWeight: "bold",
    letterSpacing: 1,
    marginVertical: 15,
  },
  infoGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginBottom: 20,
  },
  infoItem: {
    width: "33.33%",
    marginBottom: 12,
  },
  infoLabel: {
    fontSize: 9,
    fontWeight: "bold",
    color: "#666666",
    marginBottom: 2,
  },
  infoValue: {
    fontSize: 9,
    color: "#000000",
  },
  table: {
    marginTop: 15,
    marginBottom: 20,
  },
  tableHeader: {
    flexDirection: "row",
    backgroundColor: "#f5f5f5",
    borderBottomWidth: 2,
    borderBottomColor: "#333333",
    paddingVertical: 8,
    paddingHorizontal: 5,
  },
  tableRow: {
    flexDirection: "row",
    borderBottomWidth: 0.5,
    borderBottomColor: "#e0e0e0",
    paddingVertical: 6,
    paddingHorizontal: 5,
  },
  tableRowLast: {
    flexDirection: "row",
    borderBottomWidth: 2,
    borderBottomColor: "#333333",
    paddingVertical: 6,
    paddingHorizontal: 5,
  },
  tableHeaderCell: {
    fontSize: 9,
    fontWeight: "bold",
    textAlign: "center",
  },
  tableCell: {
    fontSize: 9,
    textAlign: "center",
  },
  colCode: {
    width: "20%",
  },
  colName: {
    width: "40%",
  },
  colQty: {
    width: "13%",
  },
  colPrice: {
    width: "13%",
  },
  colTotal: {
    width: "14%",
  },
  totalsSection: {
    alignSelf: "flex-end",
    width: 220,
    marginTop: 15,
  },
  totalsRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 4,
    fontSize: 9,
  },
  totalsFinal: {
    flexDirection: "row",
    justifyContent: "space-between",
    borderTopWidth: 2,
    borderTopColor: "#333333",
    paddingTop: 8,
    marginTop: 4,
    fontSize: 11,
    fontWeight: "bold",
  },
  footer: {
    marginTop: 30,
    alignItems: "center",
  },
  footerText: {
    fontSize: 8,
    color: "#666666",
    marginBottom: 4,
    textAlign: "center",
  },
  footerNote: {
    fontSize: 7,
    color: "#666666",
    marginTop: 10,
    textAlign: "center",
  },
});

export default function PurchaseOrderPDFDocument({
  orderData,
  companyInfo = {
    name: "TechCorp Solutions Ltd",
    tagline: "Procurement & Supply Chain Excellence",
    email: "contact@techcorp.co.ke",
    phone: "+254 XXX XXX XXX",
  },
  currency = "KSh",
  locale = "en-KE",
}: PurchaseOrderPDFProps) {
  const formatCurrency = (amount: number) =>
    amount.toLocaleString(locale, {
      minimumFractionDigits: 2,
      maximumFractionDigits: 2,
    });

  const formatDate = (dateString: string | Date | null) => {
    if (!dateString) return "N/A";
    return new Date(dateString).toLocaleDateString(locale, {
      year: "numeric",
      month: "long",
      day: "numeric",
    });
  };

  const subtotal = orderData.products.reduce(
    (sum, item) => sum + item.price * item.quantity,
    0
  );

  return (
    /* eslint-disable jsx-a11y/alt-text */
    <Document>
      <Page size="A4" style={styles.page}>
        {/* Header */}
        <View style={styles.header}>
          {companyInfo.logoUrl && (
            <Image
              style={styles.logo}
              src={companyInfo.logoUrl || "/images/nostorefound.jpg"}
            />
          )}
          <Text style={styles.companyName}>{companyInfo.name}</Text>
          {companyInfo.tagline && (
            <Text style={styles.companyTagline}>{companyInfo.tagline}</Text>
          )}
          {(companyInfo.email || companyInfo.phone) && (
            <Text style={styles.companyContact}>
              {[companyInfo.email, companyInfo.phone]
                .filter(Boolean)
                .join(" | ")}
            </Text>
          )}
        </View>

        <View style={styles.divider} />

        {/* Title */}
        <Text style={styles.title}>PURCHASE ORDER</Text>

        {/* Details */}
        <View style={styles.infoGrid}>
          <View style={styles.infoItem}>
            <Text style={styles.infoLabel}>Order Number:</Text>
            <Text style={styles.infoValue}>{orderData.orderNumber}</Text>
          </View>
          <View style={styles.infoItem}>
            <Text style={styles.infoLabel}>Supplier:</Text>
            <Text style={styles.infoValue}>{orderData.supplier || "N/A"}</Text>
          </View>
          <View style={styles.infoItem}>
            <Text style={styles.infoLabel}>Store:</Text>
            <Text style={styles.infoValue}>{orderData.store || "N/A"}</Text>
          </View>
          <View style={styles.infoItem}>
            <Text style={styles.infoLabel}>Status:</Text>
            <Text style={styles.infoValue}>{orderData.status}</Text>
          </View>
          <View style={styles.infoItem}>
            <Text style={styles.infoLabel}>Expected Date:</Text>
            <Text style={styles.infoValue}>
              {formatDate(orderData.dateExpected)}
            </Text>
          </View>
          <View style={styles.infoItem}>
            <Text style={styles.infoLabel}>Date Created:</Text>
            <Text style={styles.infoValue}>
              {formatDate(orderData.dateCreated)}
            </Text>
          </View>
          <View style={styles.infoItem}>
            <Text style={styles.infoLabel}>Created By:</Text>
            <Text style={styles.infoValue}>{orderData.createdBy}</Text>
          </View>
          <View style={styles.infoItem}>
            <Text style={styles.infoLabel}>Auto Generated:</Text>
            <Text style={styles.infoValue}>
              {orderData.autoGenerated ? "Yes" : "No"}
            </Text>
          </View>
        </View>

        {/* Product Table */}
        <View style={styles.table}>
          <View style={styles.tableHeader}>
            <Text style={[styles.tableHeaderCell, styles.colCode]}>
              Product ID
            </Text>
            <Text style={[styles.tableHeaderCell, styles.colName]}>
              Product Name
            </Text>
            <Text style={[styles.tableHeaderCell, styles.colQty]}>Qty</Text>
            <Text style={[styles.tableHeaderCell, styles.colPrice]}>
              Unit Price ({currency})
            </Text>
            <Text style={[styles.tableHeaderCell, styles.colTotal]}>
              Total ({currency})
            </Text>
          </View>

          {orderData.products.map((item, index) => {
            const isLast = index === orderData.products.length - 1;
            const total = item.quantity * item.price;
            return (
              <View
                key={index}
                style={isLast ? styles.tableRowLast : styles.tableRow}
              >
                <Text style={[styles.tableCell, styles.colCode]}>
                  {item.barcode || item.businessProductId}
                </Text>
                <Text style={[styles.tableCell, styles.colName]}>
                  {item.productName || "N/A"}
                </Text>
                <Text style={[styles.tableCell, styles.colQty]}>
                  {item.quantity}
                </Text>
                <Text style={[styles.tableCell, styles.colPrice]}>
                  {formatCurrency(item.price)}
                </Text>
                <Text
                  style={[
                    styles.tableCell,
                    styles.colTotal,
                    { fontWeight: "bold" },
                  ]}
                >
                  {formatCurrency(total)}
                </Text>
              </View>
            );
          })}
        </View>

        {/* Totals */}
        <View style={styles.totalsSection}>
          <View style={styles.totalsFinal}>
            <Text>TOTAL ORDER VALUE:</Text>
            <Text>
              {currency} {formatCurrency(subtotal)}
            </Text>
          </View>
        </View>

        {/* Footer */}
        <View style={styles.footer}>
          <Text style={styles.footerText}>
            This purchase order was generated by {companyInfo.name}
          </Text>
          {companyInfo.email && (
            <Text style={styles.footerText}>
              Contact: {companyInfo.email} | {companyInfo.phone}
            </Text>
          )}
          <Text style={styles.footerNote}>
            This is a system-generated document and does not require a
            signature.
          </Text>
        </View>
      </Page>
    </Document>
  );
}
